const Ziggy = {
    url: "http:\/\/localhost:8000",
    port: 8000,
    defaults: {},
    routes: {
        sitemap: { uri: "sitemap.xml", methods: ["GET", "HEAD"] },
        robots: { uri: "robots.txt", methods: ["GET", "HEAD"] },
        "lang.switch": {
            uri: "lang\/{lang}",
            methods: ["GET", "HEAD"],
            parameters: ["lang"],
        },
        login: { uri: "login", methods: ["GET", "HEAD"] },
        "auth.login": {
            uri: "{locale}\/login",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "auth.login.post": {
            uri: "{locale}\/login",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "auth.logout": {
            uri: "{locale}\/logout",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.dashboard.index": {
            uri: "{locale}\/admin",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.pages.index": {
            uri: "{locale}\/admin\/pages",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.pages.create": {
            uri: "{locale}\/admin\/pages\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.pages.store": {
            uri: "{locale}\/admin\/pages",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.pages.edit": {
            uri: "{locale}\/admin\/pages\/{page}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "page"],
            bindings: { page: "id" },
        },
        "admin.pages.update": {
            uri: "{locale}\/admin\/pages\/{page}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "page"],
            bindings: { page: "id" },
        },
        "admin.pages.destroy": {
            uri: "{locale}\/admin\/pages\/{page}",
            methods: ["DELETE"],
            parameters: ["locale", "page"],
            bindings: { page: "id" },
        },
        "admin.posts.index": {
            uri: "{locale}\/admin\/posts",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.posts.create": {
            uri: "{locale}\/admin\/posts\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.posts.store": {
            uri: "{locale}\/admin\/posts",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.posts.edit": {
            uri: "{locale}\/admin\/posts\/{post}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "post"],
            bindings: { post: "id" },
        },
        "admin.posts.update": {
            uri: "{locale}\/admin\/posts\/{post}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "post"],
            bindings: { post: "id" },
        },
        "admin.posts.destroy": {
            uri: "{locale}\/admin\/posts\/{post}",
            methods: ["DELETE"],
            parameters: ["locale", "post"],
            bindings: { post: "id" },
        },
        "admin.categories.index": {
            uri: "{locale}\/admin\/categories",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.categories.create": {
            uri: "{locale}\/admin\/categories\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.categories.store": {
            uri: "{locale}\/admin\/categories",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.categories.edit": {
            uri: "{locale}\/admin\/categories\/{category}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "category"],
        },
        "admin.categories.update": {
            uri: "{locale}\/admin\/categories\/{category}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "category"],
        },
        "admin.categories.destroy": {
            uri: "{locale}\/admin\/categories\/{category}",
            methods: ["DELETE"],
            parameters: ["locale", "category"],
        },
        "admin.media.index": {
            uri: "{locale}\/admin\/media",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.media.store": {
            uri: "{locale}\/admin\/media",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.media.update": {
            uri: "{locale}\/admin\/media\/{media}",
            methods: ["PATCH"],
            parameters: ["locale", "media"],
        },
        "admin.media.destroy": {
            uri: "{locale}\/admin\/media\/{media}",
            methods: ["DELETE"],
            parameters: ["locale", "media"],
        },
        "admin.media.folders.store": {
            uri: "{locale}\/admin\/media\/folders",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.media.folders.update": {
            uri: "{locale}\/admin\/media\/folders\/{folder}",
            methods: ["PATCH"],
            parameters: ["locale", "folder"],
            bindings: { folder: "id" },
        },
        "admin.media.folders.destroy": {
            uri: "{locale}\/admin\/media\/folders\/{folder}",
            methods: ["DELETE"],
            parameters: ["locale", "folder"],
            bindings: { folder: "id" },
        },
        "admin.media.bulk-action": {
            uri: "{locale}\/admin\/media\/bulk-action",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.projects.index": {
            uri: "{locale}\/admin\/projects",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.projects.create": {
            uri: "{locale}\/admin\/projects\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.projects.store": {
            uri: "{locale}\/admin\/projects",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.projects.edit": {
            uri: "{locale}\/admin\/projects\/{project}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "project"],
            bindings: { project: "id" },
        },
        "admin.projects.update": {
            uri: "{locale}\/admin\/projects\/{project}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "project"],
            bindings: { project: "id" },
        },
        "admin.projects.destroy": {
            uri: "{locale}\/admin\/projects\/{project}",
            methods: ["DELETE"],
            parameters: ["locale", "project"],
            bindings: { project: "id" },
        },
        "admin.clients.index": {
            uri: "{locale}\/admin\/clients",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.clients.create": {
            uri: "{locale}\/admin\/clients\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.clients.store": {
            uri: "{locale}\/admin\/clients",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.clients.edit": {
            uri: "{locale}\/admin\/clients\/{client}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "client"],
        },
        "admin.clients.update": {
            uri: "{locale}\/admin\/clients\/{client}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "client"],
        },
        "admin.clients.destroy": {
            uri: "{locale}\/admin\/clients\/{client}",
            methods: ["DELETE"],
            parameters: ["locale", "client"],
        },
        "admin.forms.index": {
            uri: "{locale}\/admin\/forms",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.forms.create": {
            uri: "{locale}\/admin\/forms\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.forms.store": {
            uri: "{locale}\/admin\/forms",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.forms.edit": {
            uri: "{locale}\/admin\/forms\/{form}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "form"],
            bindings: { form: "id" },
        },
        "admin.forms.update": {
            uri: "{locale}\/admin\/forms\/{form}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "form"],
            bindings: { form: "id" },
        },
        "admin.forms.destroy": {
            uri: "{locale}\/admin\/forms\/{form}",
            methods: ["DELETE"],
            parameters: ["locale", "form"],
            bindings: { form: "id" },
        },
        "admin.templates.index": {
            uri: "{locale}\/admin\/templates",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.templates.create": {
            uri: "{locale}\/admin\/templates\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.templates.store": {
            uri: "{locale}\/admin\/templates",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.templates.edit": {
            uri: "{locale}\/admin\/templates\/{template}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "template"],
            bindings: { template: "id" },
        },
        "admin.templates.update": {
            uri: "{locale}\/admin\/templates\/{template}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "template"],
            bindings: { template: "id" },
        },
        "admin.templates.destroy": {
            uri: "{locale}\/admin\/templates\/{template}",
            methods: ["DELETE"],
            parameters: ["locale", "template"],
            bindings: { template: "id" },
        },
        "admin.translations.index": {
            uri: "{locale}\/admin\/translations",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.translations.create": {
            uri: "{locale}\/admin\/translations\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.translations.store": {
            uri: "{locale}\/admin\/translations",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.translations.edit": {
            uri: "{locale}\/admin\/translations\/{translation}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "translation"],
        },
        "admin.translations.update": {
            uri: "{locale}\/admin\/translations\/{translation}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "translation"],
            bindings: { translation: "id" },
        },
        "admin.translations.destroy": {
            uri: "{locale}\/admin\/translations\/{translation}",
            methods: ["DELETE"],
            parameters: ["locale", "translation"],
            bindings: { translation: "id" },
        },
        "admin.languages.index": {
            uri: "{locale}\/admin\/languages",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.languages.create": {
            uri: "{locale}\/admin\/languages\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.languages.store": {
            uri: "{locale}\/admin\/languages",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.languages.edit": {
            uri: "{locale}\/admin\/languages\/{language}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "language"],
        },
        "admin.languages.update": {
            uri: "{locale}\/admin\/languages\/{language}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "language"],
            bindings: { language: "id" },
        },
        "admin.languages.destroy": {
            uri: "{locale}\/admin\/languages\/{language}",
            methods: ["DELETE"],
            parameters: ["locale", "language"],
            bindings: { language: "id" },
        },
        "admin.users.index": {
            uri: "{locale}\/admin\/users",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.users.create": {
            uri: "{locale}\/admin\/users\/create",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.users.store": {
            uri: "{locale}\/admin\/users",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.users.edit": {
            uri: "{locale}\/admin\/users\/{user}\/edit",
            methods: ["GET", "HEAD"],
            parameters: ["locale", "user"],
            bindings: { user: "id" },
        },
        "admin.users.update": {
            uri: "{locale}\/admin\/users\/{user}",
            methods: ["PUT", "PATCH"],
            parameters: ["locale", "user"],
            bindings: { user: "id" },
        },
        "admin.users.destroy": {
            uri: "{locale}\/admin\/users\/{user}",
            methods: ["DELETE"],
            parameters: ["locale", "user"],
            bindings: { user: "id" },
        },
        "admin.settings.index": {
            uri: "{locale}\/admin\/settings",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.settings.store": {
            uri: "{locale}\/admin\/settings",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.theme.index": {
            uri: "{locale}\/admin\/theme",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.colors": {
            uri: "{locale}\/admin\/theme\/colors",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.fonts": {
            uri: "{locale}\/admin\/theme\/fonts",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.sizes": {
            uri: "{locale}\/admin\/theme\/sizes",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.typography": {
            uri: "{locale}\/admin\/theme\/typography",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.effects": {
            uri: "{locale}\/admin\/theme\/effects",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        "admin.theme.store": {
            uri: "{locale}\/admin\/theme",
            methods: ["POST"],
            parameters: ["locale"],
        },
        "admin.blocks": {
            uri: "{locale}\/admin\/blocks",
            methods: ["GET", "HEAD"],
            parameters: ["locale"],
        },
        home: {
            uri: "{locale}",
            methods: ["GET", "HEAD"],
            wheres: { locale: "[a-z]{2}" },
            parameters: ["locale"],
        },
        "forms.preview": {
            uri: "{locale}\/forms\/{id}\/preview",
            methods: ["GET", "HEAD"],
            wheres: { locale: "[a-z]{2}" },
            parameters: ["locale", "id"],
        },
        "storage.local": {
            uri: "storage\/{path}",
            methods: ["GET", "HEAD"],
            wheres: { path: ".*" },
            parameters: ["path"],
        },
        "storage.local.upload": {
            uri: "storage\/{path}",
            methods: ["PUT"],
            wheres: { path: ".*" },
            parameters: ["path"],
        },
    },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
